### ISSUE TITLE
[TM-6576] - Blocking fast fonts call

### ISSUE THREAD

**Issue by rotaruandrei98** [Tapestry-Inc/design-tokens#59]
Ticket link: https://jira.tapestry.support/browse/TM-6576

After installing the latest available version, `@tapestry-inc/design-tokens@3.1.2`, in `design-tokens/coach/font-face.css` file, on the first line we are doing `@import url("https://fast.fonts.net/t/1.css?apiType=css&projectid=22d7b642-0ee0-41e4-ba50-8fc4bcba4bb4")` which is returning and empty response when we are trying to get this resource and we can also removed it because we don't need it and it's also a blocking render resource. You can also check my screenshot.
<img width="875" alt="Screenshot 2021-10-16 at 16 35 26" src="https://user-images.githubusercontent.com/87981625/137589686-aad2f707-33ee-401a-bd0d-7a54cc866173.png">

**Comment by dmerfeld** [comment]
Update: I have reached out to Monotype tech support to check on a workaround for this issue. I suspect we might be the only ones actually abiding by their font tracking guidelines so this might take awhile. I am also wondering if we included that @import later in the load sequence if that might help with performance.

I'll post updates here as I get them.

**Comment by ryanfitzer** [comment]
With the CSS approach, the `@import` can only be at the top of the file.

I know there are other ways, but it's been a while since I've used them (I no longer have Monotype access to check). There should be a JavaScript approach to loading the tracking code. Of course, that would add more complexity to the tokens by adding a `.js` file that needs to be integrated by the consumers of the package.

**Comment by dmerfeld** [comment]
Update: Monotype devs tell me that we must do this call at the top of our CSS file and there are no non-blocking call options.
